baseURL                 = "https://DNS-over-HTTPS.com/"
languageCode            = "en-us"
title                   = "DNS-over-HTTPS.com"

[params]
description             = "IETF compliant DNS-over-HTTPS service as geeky as if we are at year 8102."

[[menu.main]]
name                    = "Home"
url                     = "/"
weight                  = 10

[[menu.main]]
name                    = "Setup"
url                     = "/setup/"
weight                  = 0